# Generated by Django 6.1 on 2026-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.IntegerField(),
        ),
    ]
